{"name": "test_sum_001", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <Testcases.test_file_1.Test_001 object at 0x0000022DDD4B5B50>\n\n    def test_sum_001(self):\n        a=10\n        b=30\n        sum=a+b\n        print(sum)\n        if sum == 30:\n            assert True\n        else:\n>           assert False\nE           assert False\n\nTestcases\\test_file_1.py:14: AssertionError"}, "attachments": [{"name": "stdout", "source": "05e43ee9-d29c-4d5f-8c7e-e76498cd340c-attachment.txt", "type": "text/plain"}], "start": 1690998286733, "stop": 1690998286735, "uuid": "cf447506-c82d-4a6c-8892-02be80cb307f", "historyId": "7a9cd8b3660555471df7548d6ba79ff1", "testCaseId": "7a9cd8b3660555471df7548d6ba79ff1", "fullName": "Testcases.test_file_1.Test_001#test_sum_001", "labels": [{"name": "parentSuite", "value": "Testcases"}, {"name": "suite", "value": "test_file_1"}, {"name": "subSuite", "value": "Test_001"}, {"name": "host", "value": "Shelar"}, {"name": "thread", "value": "7628-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Testcases.test_file_1"}]}