{"name": "test_sum_001", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <Testcases.test_file_1.Test_001 object at 0x0000024CA062D290>\n\n    def test_sum_001(self):\n        a=10\n        b=30\n        sum=a+b\n        print(sum)\n        if sum == 10:\n            assert True\n        else:\n>           assert False\nE           assert False\n\nTestcases\\test_file_1.py:17: AssertionError"}, "attachments": [{"name": "stdout", "source": "68f4159a-5835-4a68-b8df-8c4054ad46fc-attachment.txt", "type": "text/plain"}], "start": 1691061584645, "stop": 1691061584647, "uuid": "d75ff118-e07e-483c-8d33-14aadccfea18", "historyId": "7a9cd8b3660555471df7548d6ba79ff1", "testCaseId": "7a9cd8b3660555471df7548d6ba79ff1", "fullName": "Testcases.test_file_1.Test_001#test_sum_001", "labels": [{"name": "parentSuite", "value": "Testcases"}, {"name": "suite", "value": "test_file_1"}, {"name": "subSuite", "value": "Test_001"}, {"name": "host", "value": "Shelar"}, {"name": "thread", "value": "14804-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Testcases.test_file_1"}]}